export const DATA = [
    {
        id: 1,
        name: 'Harry Potter (1)',
        email: 'Harry.Potter@hogwarts.com',
        submitDate: '2022-07-31',
    },
    {
        id: 2,
        name: 'Hermione Granger (2)',
        email: 'Hermione.Granger@hogwarts.com',
        submitDate: '2022-09-15',
    },
    {
        id: 3,
        name: 'Ron Weasley (3)',
        email: 'Ron.Weasley@hogwarts.com',
        submitDate: '2023-02-21',
    },
    {
        id: 4,
        name: 'Albus Dumbledore (4)',
        email: 'Albus.Dumbledore@hogwarts.com',
        submitDate: '2022-12-12',
    },
    {
        id: 5,
        name: 'Severus Snape (5)',
        email: 'Severus.Snape@hogwarts.com',
        submitDate: '2023-06-29',
    },
    {
        id: 6,
        name: 'Sirius Black (6)',
        email: 'Sirius.Black@hogwarts.com',
        submitDate: '2023-04-18',
    },
    {
        id: 7,
        name: 'Rubeus Hagrid (7)',
        email: 'Rubeus.Hagrid@hogwarts.com',
        submitDate: '2023-03-05',
    },
    {
        id: 8,
        name: 'Minerva McGonagall (8)',
        email: 'Minerva.McGonagall@hogwarts.com',
        submitDate: '2022-10-30',
    },
    {
        id: 9,
        name: 'Remus Lupin (9)',
        email: 'Remus.Lupin@hogwarts.com',
        submitDate: '2023-01-17',
    },
    {
        id: 10,
        name: 'Bellatrix Lestrange (10)',
        email: 'Bellatrix.Lestrange@hogwarts.com',
        submitDate: '2022-08-20',
    },
    {
        id: 11,
        name: 'Neville Longbottom (11)',
        email: 'Neville.Longbottom@hogwarts.com',
        submitDate: '2023-05-10',
    },
    {
        id: 12,
        name: 'Draco Malfoy (12)',
        email: 'Draco.Malfoy@hogwarts.com',
        submitDate: '2023-01-28',
    },
    {
        id: 13,
        name: 'Luna Lovegood (13)',
        email: 'Luna.Lovegood@hogwarts.com',
        submitDate: '2023-05-22',
    },
    {
        id: 14,
        name: 'Fred Weasley (14)',
        email: 'Fred.Weasley@hogwarts.com',
        submitDate: '2022-08-10',
    },
    {
        id: 15,
        name: 'George Weasley (15)',
        email: 'George.Weasley@hogwarts.com',
        submitDate: '2022-12-02',
    },
    {
        id: 16,
        name: 'Ginny Weasley (16)',
        email: 'Ginny.Weasley@hogwarts.com',
        submitDate: '2023-03-19',
    },
    {
        id: 17,
        name: 'Arthur Weasley (17)',
        email: 'Arthur.Weasley@hogwarts.com',
        submitDate: '2023-02-09',
    },
    {
        id: 18,
        name: 'Molly Weasley (18)',
        email: 'Molly.Weasley@hogwarts.com',
        submitDate: '2023-06-14',
    },
    {
        id: 19,
        name: 'Voldemort (19)',
        email: 'Voldemort@hogwarts.com',
        submitDate: '2023-05-18',
    },
    {
        id: 20,
        name: 'Dobby the House Elf (20)',
        email: 'Dobby.HouseElf@hogwarts.com',
        submitDate: '2022-11-03',
    },
    {
        id: 21,
        name: 'Lucius Malfoy (21)',
        email: 'Lucius.Malfoy@hogwarts.com',
        submitDate: '2023-01-30',
    },
    {
        id: 22,
        name: 'Narcissa Malfoy (22)',
        email: 'Narcissa.Malfoy@hogwarts.com',
        submitDate: '2023-05-26',
    },
    {
        id: 23,
        name: 'Fleur Delacour (23)',
        email: 'Fleur.Delacour@hogwarts.com',
        submitDate: '2022-07-23',
    },
    {
        id: 24,
        name: 'Cedric Diggory (24)',
        email: 'Cedric.Diggory@hogwarts.com',
        submitDate: '2022-10-18',
    },
    {
        id: 25,
        name: 'Cho Chang (25)',
        email: 'Cho.Chang@hogwarts.com',
        submitDate: '2023-04-02',
    },
    {
        id: 26,
        name: 'Colin Creevey (26)',
        email: 'Colin.Creevey@hogwarts.com',
        submitDate: '2023-04-17',
    },
    {
        id: 27,
        name: 'Rita Skeeter (27)',
        email: 'Rita.Skeeter@hogwarts.com',
        submitDate: '2023-03-16',
    },
    {
        id: 28,
        name: 'Seamus Finnigan (28)',
        email: 'Seamus.Finnigan@hogwarts.com',
        submitDate: '2023-02-12',
    },
    {
        id: 29,
        name: 'Pansy Parkinson (29)',
        email: 'Pansy.Parkinson@hogwarts.com',
        submitDate: '2023-05-06',
    },
    {
        id: 30,
        name: 'Dean Thomas (30)',
        email: 'Dean.Thomas@hogwarts.com',
        submitDate: '2022-08-25',
    },
    {
        id: 31,
        name: 'Padma Patil (31)',
        email: 'Padma.Patil@hogwarts.com',
        submitDate: '2023-06-26',
    },
    {
        id: 32,
        name: 'Parvati Patil (32)',
        email: 'Parvati.Patil@hogwarts.com',
        submitDate: '2022-09-05',
    },

];
